forge "https://forgeapi.puppetlabs.com"

mod 'hajee-ora_rac', '>= 0.6.0'
mod 'hajee/easy_type'
mod 'hajee-oracle', '>= 1.0.0'
mod 'hajee-hacks'
mod 'hajee-partition', '>= 0.0.3'
mod 'biemond-oradb'
mod 'puppetlabs-firewall'
mod 'yelp-netstdlib', :git => 'https://www.github.com/Yelp/puppet-netstdlib.git'
mod 'adrien-network'
mod 'erwbgy-ssh'
mod 'adrien/boolean'
mod 'erwbgy-limits'
mod 'puppetlabs/stdlib'
mod 'ripienaar-module_data'
